# Generated by Django 3.2.7 on 2021-09-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20210919_2246'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['api_id'], name='books_book_api_id_82a1ef_idx'),
        ),
    ]
